### ISSUE TITLE
Uncaught TypeError: Cannot use 'in' operator to search for 'length'

### ISSUE THREAD

**Issue by burtondav** [rweng/jquery-datatables-rails#198] opened 2015-10-17 14:16 UTC
I'm getting the error "Uncaught TypeError: Cannot use 'in' operator to search for 'length' in isArraylike @ jquery.self-".

It happens in these lines:

    var length = "length" in obj && obj.length,
          type = jQuery.type( obj );

        if ( type === "function" || jQuery.isWindow( obj ) ) {
            return false;
        }

A stackoverflow question states that "The versions 1.11.3 and 2.1.4 have this issue."

Jquery-rails versions, say:

    module Jquery   
        module Rails     
          VERSION = "4.0.5"     
          JQUERY_VERSION = "1.11.3"     
          JQUERY_2_VERSION = "2.1.4"     
          JQUERY_UJS_VERSION = "1.1.0"   
        end
      end

How can I fix my issue?

**Comment by rocketraceheroes** [comment] 2015-10-18 02:10
As a temporary workaround, you can lock the jquery-rails gem to 4.0.4. That works in my environment where I was getting the same issues with datatables.

**Comment by nightsurge** [comment] 2015-10-18 02:10
As a temporary workaround, you can lock the jquery-rails gem to 4.0.4. That works in my environment where I was getting the same issues with datatables.

**Comment by martinechtner** [comment] 2015-11-05 14:16
This has been fixed in datatables https://github.com/DataTables/DataTablesSrc/commit/485b259e5c02ae7 can it be integrated and a new gem cut?  For my project I need jquery-rails 4.0.5, another gem requires that version.

**Comment by dometto** [comment] 2015-11-09 21:31
:+1:

Looks like the same issue as #193.

**Comment by bartkamphorst** [comment] 2015-11-11 19:48
Yes please! @ricardodovalle @rweng Any chance you could give us a timeline for integrating https://github.com/DataTables/DataTablesSrc/commit/485b259e5c02ae7 into a new version of the jquery-datatables-rails gem? Thanks for all your work maintaining this.

**Comment by wittythemes** [comment] 2015-12-16 00:42
Confirmed locking jquery-rails gem to 4.0.4 solves it as stated by @nightsurge . Hoping this would be fixed soon

**Comment by cavpollo** [comment] 2016-01-07 23:54
As @nightsurge said, locking the gem fixes the issue:
`gem 'jquery-rails', '=4.0.4'`
(Had to do this to update the gem)
`$ bundle update jquery-rails`

+1 for a new version with the fix

**Comment by abrambailey** [comment] 2016-01-08 17:52
:heavy_plus_sign::one:

**Comment by dyeje** [comment] 2016-02-01 21:54
:+1:

**Comment by runsnbunsn** [comment] 2016-03-16 21:21
@nightsurge thx for the workaround! drove me nuts.

**Comment by istana** [comment] 2016-04-04 09:46
I believe this has been resolved with jquery-datatables-rails (3.4.0)

**Comment by bartkamphorst** [comment] 2016-04-04 11:34
Can confirm that I'm no longer seeing this issue with `v. 3.4.0`.

**Comment by rweng** [comment] 2016-04-05 09:05
Thanks!

**Closed by rweng** 2016-04-05 09:05 UTC
