### ISSUE TITLE
RoutingError No route matches [GET] "/assets/images/sort_asc.png")

### ISSUE THREAD

**Issue by zeknox** [rweng/jquery-datatables-rails#153] opened 2015-01-08 14:46 UTC
When displaying the datatable everything appears to be working properly except some of the sorting images are not getting rendered.  When I look at my console I notice the following error everytime the page is loaded.
<pre>No route matches [GET] "/assets/images/sort_asc.png")</pre>

Gemfile.lock
<pre>jquery-datatables-rails (3.1.1)</pre>

Any insight to why this is happening and how to address the issue here?

**Comment by spjsschl** [comment] 2015-01-13 19:44
I can confirm this after upgrading to Rails4

**Comment by sman591** [comment] 2015-01-15 07:21
Experiencing the same issue in Rails 3

**Comment by hammer098** [comment] 2015-01-16 19:58
i have same issue in rails 4.2.0 after running bundle update.  reverted to 2.2.3 and it is fine for now.  will watch this issue.

grep -i datatables ../../../Gemfile
gem 'jquery-datatables-rails', '~> 2.2.3'

**Comment by cgs** [comment] 2015-01-18 21:06
For me it looks like the images are getting rendered, but I'm still seeing the errors as well. Same issue in Rails 3 as well as after upgrading to Rails 4.

**Comment by simonwo** [comment] 2015-01-21 12:50
(+1) Exact same issue on a fresh Rails 4.2.0

**Comment by casiodk** [comment] 2015-01-30 10:56
same issue here

**Comment by ricardodovalle** [comment] 2015-01-30 12:07
Please, could you try the last PR?

    gem 'jquery-datatables-rails', github: 'rweng/jquery-datatables-rails'

PR are welcome :+1:

**Comment by cgs** [comment] 2015-01-30 16:56
Thanks @ricardodovalle - No error but now seeing double the sort arrows:

http://cl.ly/image/2n0H1k3a3X3H

**Comment by sman591** [comment] 2015-01-31 03:39
@ricardodovalle doesn't seem to work for me, however I can confirm the images are available under `/assets/dataTables`, such as `/assets/dataTables/sort_both.png`. The gem currently loads it directly at `/dataTables`, which is where my issue is. 

This is due to the `../` in the CSS's image url. The previous versions of jquery-datatables-rails didn't use the `../` when looking up assets - was there a reason version 3.0 introduced this url format?

**Comment by bollard** [comment] 2015-02-03 14:52
+1 Same issue here on Rails 4.1 (and 4.0)

**Comment by fabricioflores** [comment] 2015-02-04 01:55
I'm using with bootstrap 3 generator. I don't have any console error but the table don't show sorting images.

**Comment by ricardodovalle** [comment] 2015-02-06 12:00
I am not using jquery-datatables at now.

There is a new merged PR #158 from @globalkeith at master branch . 
Could you give a try and test, please?

Thank you very much,

**Comment by ricardodovalle** [comment] 2015-02-10 20:59
Any @sman591 @cgs about this issue?
Have you used after merge #158 ?

**Comment by sman591** [comment] 2015-02-10 21:33
Thanks for pinging again - just tried the new version and had no luck. But progress: it now attempts to load from `/images/sort_asc.png`, when it is actually available at `/assets/dataTables/sort_both.png`

**Comment by ricardodovalle** [comment] 2015-02-11 01:17
@globalkeith Could you help to solve it, please?

**Comment by sman591** [comment] 2015-02-11 02:17
@ricardodovalle False alarm - I `bundle clean`ed and now it seems to work locally. Going to try deploying to production tonight and confirm it solves it.

**Comment by cgs** [comment] 2015-02-11 19:33
@ricardodovalle Still seeing this:

http://cl.ly/image/2n0H1k3a3X3H

Tried a 'bundle clean'.

**Comment by zeknox** [comment] 2015-02-11 19:33
I tried to perform a bundle clean, along with a bundle update to pull down the latest repo updates for this, but still getting routing errors in rails console.

**Comment by sman591** [comment] 2015-02-12 00:45
@zeknox are you using the Git repository in your Gemfile? This fix hasn't been released to rubygems yet.

```ruby
gem 'jquery-datatables-rails', github: 'rweng/jquery-datatables-rails'
```

@cgs that looks like there might be conflicting CSS styles?

**Comment by sman591** [comment] 2015-02-12 01:03
Can confirm this fix works in production for me (Rails 3)

**Comment by ricardodovalle** [comment] 2015-03-18 02:11
Thanks, I released a new gem version to rubygems (3.2.0).

**Closed by ricardodovalle** 2015-03-18 02:11 UTC
Labels: BUG, PR WELCOME

**Comment by miguelfg** [comment] 2015-10-15 17:23
What's the solution for this??, because it's driving me nuts. 

I've download datatables manually and check it's css file, and I see that all urls pointing to images are like this:
   background-image: url("../images/sort_both.png");

And the way this gem install it, it can find it. 

However, I've placed the images in /vendor/assets/images and tried to access directly from the browser, and still no luck. This is also weird to me. Because it not seem only an error about the relative image url above.

**Comment by dstull** [comment] 2015-10-17 14:13
Here is what i did http://dstull.github.io/javascript/2015/09/06/rails-datatables-install-without-gem/

**Comment by anka** [comment] 2016-12-20 14:02
I go with another workaround described in my answer here http://stackoverflow.com/a/41244121/135160 by adding a custom route so redirect these image file requests.

**Comment by brchang** [comment] 2017-01-22 10:10
dstull solution works, but much of it is unnecessary. You can add the gems/requires/imports as you normally would just leave out the *= require dataTables/jquery.dataTables in application.css.sass. Add that file manually so that you can modify it and remove...

table.dataTable thead .sorting {
  background-image: url("sort_both.png");
}
table.dataTable thead .sorting_asc {
  background-image: url("sort_asc.png");
}
table.dataTable thead .sorting_desc {
  background-image: url("sort_desc.png");
}
table.dataTable thead .sorting_asc_disabled {
  background-image: url("sort_asc_disabled.png");
}
table.dataTable thead .sorting_desc_disabled {
  background-image: url("sort_desc_disabled.png");
}
